name: bio_conecta
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_multi_formatter: ^2.3.2
  http: ^1.2.2
  sqflite: ^2.3.3+1
  provider: ^6.0.0
  shared_preferences: ^2.3.2
  flutter_launcher_icons: ^0.14.0
  flutter_native_splash: ^2.4.1
  dio: ^5.7.0
  page_transition: ^2.1.0

flutter_native_splash:
  color: "#ffffff"
  image: 'assets/app/splashIcon.png'
  android: true
  ios: true

  android_12:
    color: "#37ab98"
    image: 'assets/app/splashIcon.png'

flutter_icons:
  image_path: "assets/app/IconTransparent.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#37ab98"
  adaptive_icon_foreground: "assets/app/IconTransparent.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  



flutter:
  uses-material-design: true
  assets:
      - assets/images/

